### ISSUE TITLE
[ENHANCEMENT] Add a Polymod.desactivate

### ISSUE THREAD

**Issue by Cheemsandfriends** [larsiusprime/polymod#77]
Imagine if you have a mod menu selection for ppl that want to load their mods.
Well, It can be easily done with some coding.
But What if you want to desactivate them?
There should be a `Polymod.desactivate` or `Polymod.deactivate` For a modLists-menu-friendly ecosystem lol

**Comment by MasterEric** [comment]
This currently isn't implemented due to aggressive caching on the part of OpenFL, see #38 for more details.

I will leave this issue up since I have been investigating possible means to clear said cache.

In the meantime, I suggest using the solution in the linked issue (close the application and reopen it to reload mods).

**Comment by Cheemsandfriends** [comment]
> This currently isn't implemented due to aggressive caching on the part of OpenFL, see #38 for more details.
> 
> I will leave this issue up since I have been investigating possible means to clear said cache.
> 
> In the meantime, I suggest using the solution in the linked issue (close the application and reopen it to reload mods).

Wouldn't be easy with the `Assets.clear()` thing of the openfl.utils.Assets import?
or do you mean like calling that without openfl?

**Comment by MasterEric** [comment]
`Polymod.unloadMod(id)` was added in version 1.4.2. Note that this is functionally the same as calling `Polymod.init` with a different modlist.
